### ISSUE TITLE
[feat]: Make DESCRIPTION expandable on marketplace.start9.com

### ISSUE THREAD

**Issue by gStart9** [Start9Labs/brochure-marketplace#9]
### Prerequisites

- [X] I have searched for existing issues that already suggest this feature.

### Describe the Feature Request

Make DESCRIPTIONs expandable:
![image](https://user-images.githubusercontent.com/106188942/207763730-4d0d9e0c-dc5a-4748-9cf5-619ba0084ee4.png)

### Describe the Use Case

These descriptions should be expandable so prospective customers can read them.

### Describe Preferred Solution

Expandable descriptions!

**Comment by BitcoinMechanic** [comment]
Currently anything after `...` in descriptions in the brochure marketplace cannot be viewed.

**Comment by waterplea** [comment]
I'll get it done today.
